windows/src/helper/utils.h
windows/src/universal_ble_plugin.cpp

bug_fix, enhancement
___
- Streamlined error handling by removing specific `std::exception` catches in favor of general catch-all blocks, enhancing robustness.
- Improved code formatting for better readability and consistency across files.
- Enhanced code cleanliness by removing unnecessary lines and adjusting exception handling in utility functions.
___
<tr>
<td>
<details>
<summary><strong>universal_ble_plugin.cpp</strong><dd><code>Refine Exception Handling and Improve Code Formatting</code>&nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
<li>Removed specific exception handling for <code>std::exception</code> in favor …

Fix windows release build compilation

---

windows/src/universal_ble_plugin.cpp

bug_fix
___
- Improved Bluetooth radio detection to iterate through all available radios, fixing a crash when no Bluetooth adapter is present.
- Added a message output to the console if Bluetooth is not available, enhancing debuggability and user feedback.
___
<tr>
<td>
<details>
<summary><strong>universal_ble_plugin.cpp</strong><dd><code>Improved Bluetooth Radio Detection and Handling</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
<li>Replaced direct Bluetooth adapter retrieval with a loop checking all <br>radios for a Bluetooth kind.<br> <li> Added a console output if …

Fix windows crash when no bluetooth adapter available

---

CHANGELOG.md
README.md
example/lib/home/home.dart
lib/src/universal_ble_web/universal_ble_web.dart
windows/CMakeLists.txt

enhancement, documentation
___
- Simplified the Bluetooth scan filter by commenting out `ManufacturerDataFilter` usage.
- Added a warning log for web scans without `ScanFilter` or empty `withServices`.
- Updated README with new sections on ensuring Bluetooth availability and detailed Scan Filters usage.
- Removed outdated web scanning instructions from README.
- Silenced the warning message for missing Nuget.exe in CMakeLists.txt for Windows.
___
<tr>
<td>
<details>
<summary><strong>home.dart</strong><dd><code>Simplify Bluetooth Scan Filter</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …

Update readme and improve logs

---

CHANGELOG.md
pubspec.yaml
windows/src/universal_ble_plugin.cpp
windows/src/universal_ble_plugin.h

enhancement
___
- Changed `DiscoverServicesAsync` method to improve performance and code readability:
- Transitioned from asynchronous to synchronous execution.
- Directly accessed GATT services and characteristics from a cached map, enhancing efficiency.
- Simplified the parsing of characteristic properties, reducing code complexity.
- Updated method signature in the header file to match the implementation changes.
___
<tr>
<td>
<details>
<summary><strong>universal_ble_plugin.cpp</strong><dd><code>Optimize Service Discovery and Characteristic Properties Parsing</code></dd></summary>
<hr>
<li>Changed …

Fix discover services on Windows

---

CHANGELOG.md
example/lib/home/widgets/scanned_item_widget.dart
example/lib/peripheral_details/peripheral_detail_page.dart
pubspec.yaml
windows/src/universal_ble_plugin.cpp
windows/src/universal_ble_plugin.h

enhancement
___
- Added a new parameter `isConnectable` to the `pushUniversalScanResult` function to enhance filtering of BLE devices based on their connectability.
- Updated calls to `pushUniversalScanResult` throughout the code to pass the `isConnectable` flag, improving the management of BLE device discovery.
- Modified the `BluetoothLEWatcher_Received` method to include parsing and conditional handling of manufacturer data based on device connectability.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement
</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>universal_ble_plugin.cpp</strong><dd><code>Enhance BLE Scan Result Handling with Connectability Check</code></dd></summary>
<hr> …

Improve manufacturer data discovery on Windows

---

CHANGELOG.md
lib/src/universal_ble_linux/universal_ble_linux.dart
pubspec.yaml

enhancement
___
- Removed the import of the `collection` package to reduce dependencies and potentially improve performance.
- Refactored the `_getCharacteristic` and `_findDeviceById` methods to use native Dart list handling (`cast` and `firstWhere`) instead of relying on the `collection` package's `firstWhereOrNull`.
___
<tr>
<td>
<details>
<summary><strong>universal_ble_linux.dart</strong><dd><code>Remove `collection` dependency and refactor method implementations</code></dd></summary>
<hr>
lib/src/universal_ble_linux/universal_ble_linux.dart
<li>Removed dependency on <code>collection</code> package by deleting its import.<br> <li> Updated …

Remove dependency on collection

---

CHANGELOG.md
README.md
example/lib/home/home.dart
lib/src/ble_command_queue.dart
lib/src/models/model_exports.dart
lib/src/models/queue_type.dart
lib/src/queue.dart
lib/src/universal_ble.dart
lib/src/universal_ble_platform_interface.dart
lib/universal_ble.dart
pubspec.yaml

Enhancement, Documentation
___
- Introduced `QueueType` enum to manage different queue types: none, perDevice, global.
- Refactored command queue implementation to support multiple queue types.
- Updated UI components to reflect the current queue type.
- Improved documentation with examples for setting queue type and handling queue updates.
- Updated version to 0.9.12 and added changelog entry.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement
</strong></td><td><details><summary>8 files</summary><table>
<tr>
<td>
<details>
<summary><strong>home.dart</strong><dd><code>Add queue type management and update UI accordingly.</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
example/lib/home/home.dart
<li>Replaced …

Add queue per device

---

CHANGELOG.md
darwin/Classes/UniversalBlePlugin.swift

Fixes https://github.com/Navideck/universal_ble/issues/47
___
enhancement
___
- Added an `options` dictionary to enable duplicate peripheral discovery during BLE scanning by setting `CBCentralManagerScanOptionAllowDuplicatesKey` to `true`.
- Updated the `scanForPeripherals` method to include the new `options` parameter.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement
</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>UniversalBlePlugin.swift</strong><dd><code>Enable duplicate peripheral discovery in BLE scanning</code>&nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
darwin/Classes/UniversalBlePlugin.swift
<li>Added <code>options</code> dictionary with <br><code>CBCentralManagerScanOptionAllowDuplicatesKey</code> …

Set CBCentralManagerScanOptionAllowDuplicatesKey to true

---

CHANGELOG.md
android/src/main/kotlin/com/navideck/universal_ble/UniversalBleHelper.kt
android/src/main/kotlin/com/navideck/universal_ble/UniversalBlePlugin.kt
darwin/Classes/UniversalBlePlugin.swift
pubspec.yaml

Enhancement, Bug fix
___
- Added `DeviceDisconnectedError` for better error handling in Android.
- Improved cleanup logic on disconnection for both Android and Apple.
- Renamed several future result classes for clarity.
- Added error handling for `requestMtu` and `discoverServices` methods in Android.
- Updated changelog and version number to 0.10.1.
___
<tr>
<td>
<details>
<summary><strong>UniversalBleHelper.kt</strong><dd><code>Improve error handling and future result classes</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
android/src/main/kotlin/com/navideck/universal_ble/UniversalBleHelper.kt
<li>Added …

Improve error handling and disconnection events

---

.vscode/launch.json
CHANGELOG.md
README.md
example/lib/home/home.dart
example/lib/home/widgets/scan_filter_widget.dart
example/lib/peripheral_details/peripheral_detail_page.dart
example/pubspec.lock
lib/src/models/ble_device.dart
lib/src/universal_ble.dart
lib/src/universal_ble_platform_interface.dart
lib/src/universal_ble_web/universal_ble_web.dart

Enhancement, Documentation, Bug fix
___
- Improved logging for BLE scan results by replacing `debugPrint` with `log`.
- Added `withManufacturerData` filter to scan filter widget.
- Added error handling for service discovery in peripheral detail page.
- Added `receivesAdvertisements` property to `BleDevice` and method to `UniversalBle`.
- Improved advertisement handling and cleanup on web.
- Added new launch configuration for web development in VSCode.
- Updated changelog for new features and improvements.
- Fixed typos and clarified usage of `withServices` parameter on web in README.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details><summary>6 files</summary><table>
<tr>
<td>
<details> …

Receive advertisement events on web

---

example/lib/peripheral_details/peripheral_detail_page.dart
lib/src/universal_ble_web/universal_ble_web.dart

Support IOS [Bluefy](https://apps.apple.com/de/app/bluefy-web-ble-browser/id1492822055) browser
Support [web_view_ble](https://pub.dev/packages/web_view_ble)
___
Enhancement, Bug fix
___
- Added a conditional check for `BleOutputProperty` in `peripheral_detail_page.dart` to handle write operations more effectively.
- Introduced a service cache in `universal_ble_web.dart` to improve performance and refactored related methods to utilize this cache.
- Created `_UniversalWebBluetoothService` class to encapsulate service and characteristic management.
- Improved error handling and code readability.
___
<tr>
<td>
<details> …

Improve web support

---

CHANGELOG.md
android/src/main/kotlin/com/navideck/universal_ble/UniversalBleHelper.kt
android/src/main/kotlin/com/navideck/universal_ble/UniversalBlePlugin.kt
example/pubspec.lock

Bug fix
___
- Added a null check for `BluetoothGattDescriptor` to handle cases where the descriptor is not found.
- Updated the logic to ensure that devices which do not require their CCCD to update are handled correctly.
- Improved error logging to provide more information when descriptor write operations fail.
- Ensured backward compatibility by using deprecated methods conditionally based on the Android version.
___
<tr>
<td>
<details>
<summary><strong>UniversalBleHelper.kt</strong><dd><code>Fix notification setup for characteristics without CCCD</code>&nbsp; &nbsp; </dd></summary>
<hr>
android/src/main/kotlin/com/navideck/universal_ble/UniversalBleHelper.k …

Fix Android notification for characteristics without CCCD

---

.vscode/settings.json
CHANGELOG.md
README.md
darwin/Classes/UniversalBlePlugin.swift
example/lib/data/capabilities.dart
example/lib/data/mock_universal_ble.dart
example/lib/home/home.dart
example/lib/peripheral_details/peripheral_detail_page.dart
example/macos/Runner/AppDelegate.swift
example/pubspec.lock
lib/src/models/ble_command.dart
lib/src/models/model_exports.dart
lib/src/universal_ble.dart
lib/src/universal_ble_linux/universal_ble_linux.dart
lib/src/universal_ble_pigeon/universal_ble_pigeon_channel.dart
lib/src/universal_ble_platform_interface.dart
lib/src/universal_ble_web/universal_ble_web.dart
pubspec.yaml

Enhancement, Documentation
___
- Enabled pairing API support for Cupertino platform by removing conditional checks.
- Always display pairing buttons in the peripheral detail page regardless of platform.
- Improved code level documentation by adding dots for better readability.
- Implemented pairing logic for Apple devices, including error handling and logging for debugging.
- Updated the changelog to include version 0.10.1 with new features and improvements.
- Updated the README to reflect new pairing and unpairing support details.
___
<tr>
<td>
<details>
<summary><strong>capabilities.dart</strong><dd><code>Enable pairing API support for Cupertino …

Implement pairing on Apple

---

CHANGELOG.md
README.md
example/lib/data/mock_universal_ble.dart
example/lib/peripheral_details/peripheral_detail_page.dart
lib/src/universal_ble.dart
lib/src/universal_ble_linux/universal_ble_linux.dart
lib/src/universal_ble_pigeon/universal_ble_pigeon_channel.dart
lib/src/universal_ble_platform_interface.dart

Enhancement, Documentation
___
- Removed the `error` parameter from `updatePairingState` and related methods across multiple files.
- Simplified `_handlePairingStateChange` by removing error handling.
- Added `_pairStateMap` to track pairing state in the platform interface.
- Updated the `CHANGELOG.md` to document the breaking change.
- Updated the `README.md` to reflect the changes in `onPairingStateChange`.
___
<tr>
<td>
<details>
<summary><strong>mock_universal_ble.dart</strong><dd><code>Remove error parameter from <code>updatePairingState</code> in mock BLE <br>implementation.</code></dd></summary>
<hr>
example/lib/data/mock_universal_ble.dart
- …

Remove error from onPairingStateChange

---

lib/src/models/ble_capabilities.dart
lib/src/universal_ble.dart

- Allow pairing on all platforms
- Mark Web/Linux as not supporting in-app pairing
___
enhancement
___
- Updated the `BleCapabilities` class to clarify that pairing is not supported on Web/Windows and Web/Linux, except for devices requiring passkey pairing.
- Modified the logic to include Web/Linux as an unsupported platform for in-app pairing.
- Updated the `pair` method in `UniversalBle` to remove the `UnsupportedError` and clarify the conditions under which pairing is supported.
- Enhanced documentation to reflect the changes in platform support for pairing.
___
<tr>
<td>
<details>
<summary><strong>ble_capabilities.dart</strong><dd><code>Update …

Make supportsInAppPairing more accurate

---

CHANGELOG.md
example/lib/peripheral_details/peripheral_detail_page.dart
lib/src/models/ble_capabilities.dart
lib/src/universal_ble_pigeon/universal_ble.g.dart

enhancement, documentation
___
- Renamed `supportsInAppPairing` to `supportsAllInAppPairingKinds` in `BleCapabilities` to better reflect the supported security levels.
- Updated the enabling condition for a button in `PeripheralDetailPage` to use the new `supportsAllInAppPairingKinds`.
- Improved code readability by reformatting lines and adjusting spacing in `universal_ble.g.dart`.
- Documented the breaking change in `CHANGELOG.md` regarding the renaming of in-app pairing capabilities.
___
<tr>
<td>
<details>
<summary><strong>peripheral_detail_page.dart</strong><dd><code>Update button enabling condition for pairing</code>&nbsp; &nbsp; &nbsp; &nbsp; …

Rename in-app pairing capabilities

---

example/pubspec.lock
lib/src/universal_ble_linux/universal_ble_linux.dart

enhancement, bug_fix
___
- Improved the BLE device filtering mechanism by simplifying the scan filter logic and removing unnecessary custom filter checks.
- Added stream subscriptions to handle device addition and removal events, improving the responsiveness of the application.
- Implemented proper setup and disposal of listeners to manage device events efficiently.
- Removed redundant code, including an extension method for checking custom filters, to streamline the codebase.
___
<tr>
<td>
<details>
<summary><strong>universal_ble_linux.dart</strong><dd><code>Improve BLE device filtering and event handling in Linux</code>&nbsp; </dd></summary>
<hr> …

Fix multiple app filtering in Linux

---

CHANGELOG.md
example/pubspec.lock
pubspec.yaml

Addresses https://github.com/Navideck/universal_ble/issues/101
___
enhancement, dependencies
___
- Updated the `flutter_web_bluetooth` dependency in `pubspec.yaml` to version 1.0.0, ensuring compatibility with the latest features and improvements.
- This change addresses the need to keep dependencies up-to-date as per the related ticket.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Dependencies</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>pubspec.yaml</strong><dd><code>Update `flutter_web_bluetooth` dependency to version 1.0.0</code></dd></summary>
<hr>
pubspec.yaml
<li>Updated <code>flutter_web_bluetooth</code> dependency from version 0.2.2 to 1.0.0.<br>
</details>
</td>
<td><a …

Bump flutter_web_bluetooth to 1.0.0

---

android/src/main/kotlin/com/navideck/universal_ble/UniversalBlePlugin.kt

bug_fix
___
- Added a call to `gatt.close()` in the `cleanConnection` method to ensure proper cleanup of Bluetooth GATT connections after disconnection.
- This change addresses potential resource leaks by ensuring that the GATT connection is fully closed.
___
<tr>
<td>
<details>
<summary><strong>UniversalBlePlugin.kt</strong><dd><code>Ensure proper cleanup of Bluetooth GATT connections</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
android/src/main/kotlin/com/navideck/universal_ble/UniversalBlePlugin.kt
<li>Added <code>gatt.close()</code> after <code>gatt.disconnect()</code> in <code>cleanConnection</code> method.<br> <li> Ensures proper …

Fix android cleanup after disconnection

---

android/src/main/kotlin/com/navideck/universal_ble/SafeScanner.kt
android/src/main/kotlin/com/navideck/universal_ble/UniversalBlePlugin.kt

enhancement
___
- Introduced a new `SafeScanner` class to manage Bluetooth scanning frequency and prevent excessive scanning.
- Integrated `SafeScanner` into the `UniversalBlePlugin` to replace direct Bluetooth scanner calls.
- Implemented logic to delay scans if they occur too frequently, enhancing the robustness of the scanning process.
- Added error handling for scan failures to improve reliability.
___
<tr>
<td>
<details>
<summary><strong>SafeScanner.kt</strong><dd><code>Add SafeScanner class to manage Bluetooth scan frequency</code>&nbsp; </dd></summary>
<hr>
android/src/main/kotlin/com/navideck/universal_ble/SafeScanner.kt
<li>Introduced a new …

Handle Android scan abuse

---

android/src/main/kotlin/com/navideck/universal_ble/UniversalBleHelper.kt
android/src/main/kotlin/com/navideck/universal_ble/UniversalBlePlugin.kt

bug_fix
___
- Fixed a bug in `UniversalBleHelper.kt` by adding null safety to the `getCharacteristic` method to prevent potential null pointer exceptions.
- In `UniversalBlePlugin.kt`, moved the `gatt.close()` call to ensure it is executed after the gatt is disconnected, improving the cleanup process.
- Added a log statement to track when a gatt is closed, aiding in debugging and monitoring.
___
<tr>
<td>
<details>
<summary><strong>UniversalBleHelper.kt</strong><dd><code>Add null safety to BluetoothGatt getCharacteristic method</code></dd></summary>
<hr>
android/src/main/kotlin/com/navideck/universal_ble/UniversalBleHelper.kt
<li>Modified …

Fix Android cleanup on gatt disconnect

---

lib/src/universal_ble_linux/universal_ble_linux.dart
lib/src/universal_ble_web/universal_ble_web.dart

enhancement, bug fix
___
- Removed exceptions for already notifying characteristics in both Linux and Web implementations, replacing them with logging or simplified logic.
- Updated the key format for characteristic subscriptions and streams to use underscores instead of hyphens.
- Enhanced the logic for starting and stopping notifications, ensuring proper cancellation of existing subscriptions or streams.
___
<tr>
<td>
<details>
<summary><strong>universal_ble_linux.dart</strong><dd><code>Enhance notification handling and logging in Linux BLE</code>&nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
lib/src/universal_ble_linux/universal_ble_linux.dart
<li>Removed …

Remove "Characteristic already notifying" error

---

.vscode/launch.json
windows/src/universal_ble_plugin.cpp
windows/src/universal_ble_plugin.h

Bug fix, Enhancement
___
- Improved the handling of Bluetooth availability state by adding an initialization check and updating the logic for determining the state.
- Introduced an `initialized` flag in the `UniversalBlePlugin` class to track initialization status.
- Added a new launch configuration for Dart in release mode in the `.vscode/launch.json` file.
___
<tr>
<td>
<details>
<summary><strong>universal_ble_plugin.cpp</strong><dd><code>Improve Bluetooth availability state handling and initialization</code></dd></summary>
<hr>
<li>Added initialization check for Bluetooth availability state.<br> <li> Updated logic for …

Fix Windows Bluetooth availability state in Release build

---

android/src/main/kotlin/com/navideck/universal_ble/UniversalBleFilterUtil.kt
darwin/Classes/UniversalBlePlugin.swift
windows/src/universal_ble_plugin.cpp

bug_fix
___
- Fixed the logic in the Windows BLE plugin to correctly handle filters with multiple services.
- Added a comment to clarify that the native filter supports only one service.
___
<tr>
<td>
<details>
<summary><strong>universal_ble_plugin.cpp</strong><dd><code>Fix service filter logic in Windows BLE plugin</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
<li>Updated the condition to check for multiple services in the filter.<br> <li> Added a comment clarifying the native filter's support for only one <br>service.<br>
</details>
</td>
<td><a …

Fix Windows filter with services

---

darwin/Classes/UniversalBlePlugin.swift
example/pubspec.lock

Enhancement
___
- Introduced `findPeripheral` method to retrieve peripherals by UUID.
- Updated `getPeripheral` to use `findPeripheral` for better device retrieval.
- Added `saveCache` method to cache discovered peripherals consistently.
- Replaced direct dictionary access with `findPeripheral` for robustness.
___
<tr>
<td>
<details>
<summary><strong>UniversalBlePlugin.swift</strong><dd><code>Improved peripheral retrieval and caching logic</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
darwin/Classes/UniversalBlePlugin.swift
<li>Added <code>findPeripheral</code> method for UUID-based peripheral …

Use retrievePeripherals on Mac to communicate with device without scan

---

CHANGELOG.md
android/src/main/kotlin/com/navideck/universal_ble/UniversalBleHelper.kt
android/src/main/kotlin/com/navideck/universal_ble/UniversalBlePlugin.kt

Enhancement, Bug fix
___
- Improved BluetoothGatt management by replacing `knownGatts` list with a `Map`.
- Added utility functions for managing BluetoothGatt cache.
- Enhanced connection state handling for better app-device synchronization.
- Refactored service discovery logic for improved error handling.
___
<tr>
<td>
<details>
<summary><strong>UniversalBleHelper.kt</strong><dd><code>Refactor BluetoothGatt management utilities</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
android/src/main/kotlin/com/navideck/universal_ble/UniversalBleHelper.kt
<li>Replaced …

Improve Android bluetoothGatt management

---

CHANGELOG.md
lib/src/ble_command_queue.dart
lib/src/models/ble_connection_update.dart
lib/src/universal_ble.dart
lib/src/universal_ble_platform_interface.dart

Enhancement, Bug fix
___
- Added error handling for callback invocations across multiple methods.
- Introduced `deviceId` field in `BleConnectionUpdate` class.
- Improved connection stream handling in `UniversalBlePlatform`.
- Enhanced error handling during BLE connection and disconnection processes.
___
<tr>
<td>
<details>
<summary><strong>ble_command_queue.dart</strong><dd><code>Add error handling for queue update callbacks</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
lib/src/ble_command_queue.dart
<li>Wrapped <code>onQueueUpdate</code> callback in a try-catch block.<br> <li> Prevented …

Improve callbacks error handling

---

lib/src/universal_ble_linux/universal_ble_linux.dart

make sure getSystemDevices connects the bluez client first. this ensures that the list of devices is correctly populated.

fix: linux: getSystemDevices (issue #153)

---

example/android/.gitignore
example/android/app/build.gradle
example/android/gradle/wrapper/gradle-wrapper.properties
example/android/settings.gradle
example/ios/Podfile.lock
example/ios/Runner.xcodeproj/project.pbxproj
example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
example/ios/Runner/AppDelegate.swift
example/pubspec.lock
example/pubspec.yaml

I couldn't run the example on Android:
```
Warning: Flutter support for your project's Android Gradle Plugin version (7.3.0) will soon be dropped. Please upgrade your Android Gradle Plugin version to a version of at least 7.3.1 soon.
Alternatively, use the flag "--android-skip-build-dependency-validation" to bypass this check.
Potential fix: Your project's AGP version is typically defined in the plugins block of the `settings.gradle` file (/media/ramdisk/universal_ble_darwin_name_fix/example/android/settings.gradle), by a plugin with the id of com.android.application. 
If you don't see a plugins block, your project was likely created with an older template version. In this case it is most likely defined in the top-level build.gradle file …
```

example: Fix Android builds
